### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [kieu-avo/kan_kentei#67]
@kieu-avo 
お疲れ様です！
以下、MVPリリースレビューになります！

### 技術
`MiniMagick`や`CarrierWave`を使って画像のアップロードやリサイズ、`autocomplete`を使ってユーザーのアクションの負担を減らしたりなど、**機能に対して技術をしっかり使えている**印象です。
機能の追加は、本リリースに向けてREADMEに記載してある「その後の機能」を中心に実装していきましょう。
- また、コードが冗長なファイル（主にコントローラーやjsのファイル）がありますので、リファクタリングをしてあげるとコードを見た際、印象も良さそうだと思いました。

### ユーザビリティ
ユーザービリティも非常に高いアプリケーションだと思います。
使用させていただいて、各機能への導線や使い方の案内文など、ユーザーのことを考えてアプリケーションを作れていると思います。

その上でユーザービリティの点で細かい点になりますが、以下FBになります。

- Topページを開いた瞬間、PCの画面をヘッダーと画像で大部分を占めていまい、何をすればいいか迷ってしまうところがありました。ファーストビューで「勘検定」というアプリだと伝わると良いと思いました。（ここは他のサービスがどのようにTOPページを表示しているか見てみても良さそうです。）

- `受験カテゴリ`から「勘検定」を受験する際、受験前にレビュー項目を表示するページをがあると思うのですが、こちらもファーストビューですと「受験していないがレビューするページ」と誤解が生まれてしまいそうに思いました。なので、「受験後に表示している項目でレビューしてほしい」という内容で案内を追加してあげると良さそうです。

以上です！
非常にユーザービリティの高い、使いやすいアプリケーションだと思いました！
LGTMです！

また上記内容を実装するにあたり、スケジュールを立ててみてください。
スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by kieu-avo** [comment]
@tmtkzk0823 
お疲れ様です！レビューを確認致しました。
どこが分かりづらいのか自分では気付けなかったので、ご指摘いただき、ありがとうございます！


技術の部分で1点ご質問があります。

> また、コードが冗長なファイル（主にコントローラーやjsのファイル）がありますので、リファクタリングをしてあげるとコードを見た際、印象も良さそうだと思いました。

→jsのファイルの冗長ですが、reviews.jsのことでしょうか？



なお、アドバイス頂いたところの実装ですが、11月24日を目処に完了させる予定です。

ご確認よろしくお願い致します。

**Comment by tmtkzk0823** [comment]
`raty.js`があると思いますが、こちらファイルに記述してある内容は全て使用している状態でしょうか？
（かなり長いので使っていない記述もあるのかなと思い質問させていただきました。）

> なお、アドバイス頂いたところの実装ですが、11月24日を目処に完了させる予定です。
こちら承知しました！
追加で申し訳ないのですが、本リリース予定の日程も教えていただいてよろしいですか？

**Comment by kieu-avo** [comment]
ご確認ありがとうございます！

> raty.jsがあると思いますが、こちらファイルに記述してある内容は全て使用している状態でしょうか？
（かなり長いので使っていない記述もあるのかなと思い質問させていただきました。）

ratyという外部のライブラリを使用しているのでが、コードをいじらない方がいいと思っていました。不要と思うところを削除してみます。通常、外部のライブラリからダウンロードしたファイルにコードの削除や追加などのカスタマイズはできるのでしょうか（初歩的な質問で申し訳ありません！）？

> 追加で申し訳ないのですが、本リリース予定の日程も教えていただいてよろしいですか？

本リリースは12月16日を目処にと考えております！

今後のスケジュールですが、以下の認識で大丈夫でしょうか？
ご指摘頂いた点を実装する　→　講師の方に確認頂く　→問題なかったらMVPリリースをする

**Comment by tmtkzk0823** [comment]
> ratyという外部のライブラリを使用しているのでが、コードをいじらない方がいいと思っていました。不要と思うところを削除してみます。通常、外部のライブラリからダウンロードしたファイルにコードの削除や追加などのカスタマイズはできるのでしょうか（初歩的な質問で申し訳ありません！）？

できるものもあると思います！
ですが、おっしゃる通り、外部ライブラリのコードを削除や修正し、エラーが出てしまうのも心配だと思うので、raty.jsを修正するためのissueを作成し、そのためのブランチを切って作業すると良いと思います。
（挙動がおかしくなった場合、そのブランチを破棄してしまえば元に戻るので！）
もし難しそうであれば、ライブラリ側がコメントアウトで記載してある部分をを消すだけでも良いと思います。

> 本リリースは12月16日を目処にと考えております！
今後のスケジュールですが、以下の認識で大丈夫でしょうか？
ご指摘頂いた点を実装する　→　講師の方に確認頂く　→問題なかったらMVPリリースをする　

本リリースの日程、承知しました。ありがとうございます！
こちらのMVPリリースレビューでLGTMを出させていただきましたので、確認なしでMVPリリースしていただいて大丈夫です。
上記修正点は、本リリース時までにissueとして書いていただき、修正していただければと思います。
